apiVersion: v1
kind: Service
metadata:
  name: {{ template "future.fullname" . }}-scheduler
  labels:
    app: {{ template "future.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "future.chart" . }}
    component: scheduler
spec:
  ports:
    - name: {{ template "future.fullname" . }}-master
      port: {{ .Values.scheduler.RfuturePort }}
      targetPort: {{ .Values.scheduler.RfuturePort }}
    - name: {{ template "future.fullname" . }}-rstudio
      port: {{ .Values.scheduler.servicePort }}
      targetPort: {{ .Values.scheduler.servicePort }}
      {{- if .Values.scheduler.nodePort }}
      nodePort: {{ .Values.scheduler.nodePort }}
      {{ end }}
  selector:
    app: {{ template "future.name" . }}
    release: {{ .Release.Name | quote }}
    component: scheduler
  type: {{ .Values.scheduler.serviceType }}
